apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-agent
  namespace: REPLACE-THIS-WITH-NAMESAPCE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-agent
    spec:
      containers:
      - image: drone/agent:latest
        imagePullPolicy: Always
        name: drone-agent
        volumeMounts:
          # Enables Docker in Docker
          - name: docker-socket
            mountPath: /var/run/docker.sock
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: DRONE_RPC_SERVER
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.rpc.url
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: server.secret
        - name: DRONE_RUNNER_CAPACITY
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: agent.max
        - name: DRONE_LOGS_DEBUG
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: agent.debug

      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock