apiVersion: v1
kind: Service
metadata:
  name: drone-service
  namespace: REPLACE-THIS-WITH-NAMESAPCE
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: drone-server